DEFAULT_LIVESTOCK_ITEMS = [
    "Meat of asses, fresh or chilled (indigenous)",
    "Meat of buffalo, fresh or chilled (indigenous)",
    "Meat of camels, fresh or chilled (indigenous)",
    "Meat of chickens, fresh or chilled (indigenous)",
    "Meat of ducks, fresh or chilled (indigenous)",
    "Meat of geese, fresh or chilled (indigenous)",
    "Meat of goat, fresh or chilled (indigenous)",
    "Meat of mules, fresh or chilled (indigenous)",
    "Meat of other domestic camelids, fresh or chilled (indigenous)",
    "Meat of pig with the bone, fresh or chilled (indigenous)",
    "Meat of pigeons and other birds n.e.c., fresh, chilled or frozen (indigenous)",
    "Meat of rabbits and hares, fresh or chilled (indigenous)",
    "Meat of sheep, fresh or chilled (indigenous)",
    "Meat of turkeys, fresh or chilled (indigenous)",
    "Horse meat, fresh or chilled (indigenous)",
    "Hen eggs in shell, fresh",
    "Eggs from other birds in shell, fresh, n.e.c.",
    "Game meat, fresh, chilled or frozen",
    "Meat of cattle with the bone, fresh or chilled",
    "Meat of chickens, fresh or chilled",
    "Meat of goat, fresh or chilled",
    "Meat of pig with the bone, fresh or chilled",
    "Meat of sheep, fresh or chilled",
    "Meat of turkeys, fresh or chilled",
    "Meat of camels, fresh or chilled",
    "Horse meat, fresh or chilled",
    "Meat of rabbits and hares, fresh or chilled",
    "Natural honey",
    "Other meat n.e.c. (excluding mammals), fresh, chilled or frozen",
]

DEFAULT_CROP_ITEMS = [
    "Apples",
    "Apricots",
    "Barley",
    "Beans, dry",
    "Broad beans and horse beans, green",
    "Cabbages",
    "Cantaloupes and other melons",
    "Carrots and turnips",
    "Cauliflowers and broccoli",
    "Cherries",
    "Chestnuts, in shell",
    "Chillies and peppers, green (Capsicum spp. and Pimenta spp.)",
    "Cucumbers and gherkins",
    "Dates",
    "Eggplants (aubergines)",
    "Figs",
    "Grapes",
    "Green garlic",
    "Leeks and other alliaceous vegetables",
    "Lemons and limes",
    "Lettuce and chicory",
    "Maize (corn)",
    "Oats",
    "Okra",
    "Olives",
    "Onions and shallots, dry (excluding dehydrated)",
    "Onions and shallots, green",
    "Oranges",
    "Other beans, green",
    "Other fruits, n.e.c.",
    "Other nuts (excluding wild edible nuts and groundnuts), in shell, n.e.c.",
    "Other vegetables, fresh n.e.c.",
    "Peaches and nectarines",
    "Pears",
    "Peas, green",
    "Plums and sloes",
    "Potatoes",
    "Pumpkins, squash and gourds",
    "Quinces",
    "Raw milk of cattle",
    "Raw milk of goats",
    "Raw milk of sheep",
    "Rice",
    "Rye",
    "Shorn wool, greasy, including fleece-washed shorn wool",
    "Soya beans",
    "Spinach",
    "Sunflower seed",
    "Tangerines, mandarins, clementines",
    "Tomatoes",
    "Unmanufactured tobacco",
    "Watermelons",
    "Wheat",
    "Non Food",
    "Oilcrops Primary",
    "Roots and Tubers, Total",
    "Sugar Crops Primary",
    "Artichokes",
    "Broad beans and horse beans, dry",
    "Chick peas, dry",
    "Chillies and peppers, dry (Capsicum spp., Pimenta spp.), raw",
    "Lentils, dry",
    "Other citrus fruit, n.e.c.",
    "Other pulses n.e.c.",
    "Peas, dry",
    "Seed cotton, unginned",
    "Sorghum",
    "Triticale",
    "Vetches",
    "Bananas",
    "Cassava, fresh",
    "Coffee, green",
    "Groundnuts, excluding shelled",
    "Millet",
    "Pineapples",
    "Sweet potatoes",
    "Mangoes, guavas and mangosteens",
    "Yams",
    "Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw",
    "Asparagus",
    "Beeswax",
    "Canary seed",
    "Linseed",
    "MatÃ© leaves",
    "Pomelos and grapefruits",
    "Strawberries",
    "Sugar cane",
    "Tea leaves",
    "Walnuts, in shell",
    "Mushrooms and truffles",
    "Almonds, in shell",
    "Avocados",
    "Cow peas, dry",
    "Currants",
    "Green corn (maize)",
    "Hop cones",
    "Kiwi fruit",
    "Lupins",
    "Other berries and fruits of the genus vaccinium n.e.c.",
    "Papayas",
    "Persimmons",
    "Pistachios, in shell",
    "Rape or colza seed",
    "Raspberries",
    "Safflower seed",
    "Gooseberries",
    "Meat of ducks, fresh or chilled",
    "Meat of geese, fresh or chilled",
    "Other oil seeds, n.e.c.",
    "Poppy seed",
    "Sour cherries",
    "Sugar beet",
    "Hazelnuts, in shell",
    "Silk-worm cocoons suitable for reeling",
    "Areca nuts",
    "Coconuts, in shell",
    "Ginger, raw",
    "Jute, raw or retted",
    "Meat of buffalo, fresh or chilled",
    "Raw milk of buffalo",
    "Sesame seed",
    "String beans",
    "Buckwheat",
    "Cereals n.e.c.",
    "Cranberries",
    "Chicory roots",
    "Cashew nuts, in shell",
    "Cocoa beans",
    "Edible roots and tubers with high starch or inulin content, n.e.c., fresh",
    "Yautia",
    "Taro",
    "Mustard seed",
    "Nutmeg, mace, cardamoms, raw",
    "Other stimulant, spice and aromatic crops, n.e.c.",
    "Natural rubber in primary forms",
    "Pepper (Piper spp.), raw",
    "Plantains and cooking bananas",
    "Quinoa",
    "Brazil nuts, in shell",
    "Cashewapple",
    "Castor oil seeds",
    "Kenaf, and other textile bast fibres, raw or retted",
    "Oil palm fruit",
    "Other fibre crops, raw, n.e.c.",
    "Other tropical fruits, n.e.c.",
    "Ramie, raw or retted",
    "Sisal, raw",
    "Tung nuts",
    "Peppermint, spearmint",
    "Bambara beans, dry",
    "Fonio",
    "Karite nuts (sheanuts)",
    "Pigeon peas, dry",
    "Blueberries",
    "Meat of asses, fresh or chilled",
    "Meat of mules, fresh or chilled",
    "Melonseed",
    "Other stone fruits",
    "Kola nuts",
    "Mixed grain",
    "Locust beans (carobs)",
    "Meat of pigeons and other birds n.e.c., fresh, chilled or frozen",
    "Abaca, manila hemp, raw",
    "Other meat of mammals, fresh or chilled",
    "Agave fibres, raw, n.e.c.",
    "Cinnamon and cinnamon-tree flowers, raw",
    "Cloves (whole stems), raw",
    "Vanilla, raw",
    "Raw milk of camel",
    "Pyrethrum, dried flowers",
    "Meat of other domestic camelids, fresh or chilled",
    "True hemp, raw or retted",
    "Kapok fruit",
    "Other pome fruits",
    "Hempseed",
    "Meat of cattle with the bone, fresh or chilled (indigenous)",
    "Meat of other domestic rodents, fresh or chilled",
    "Other sugar crops n.e.c.",
]
